version: 2
project_name: figlet-go

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: figlet.go
    binary: figlet
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    formats:
      - tar.gz

nfpms:
  - id: figlet-go
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://leandrosf.com
    maintainer: Leandro Ferreira <leandrodsferreira@gmail.com>
    description: FIGlet - A Go implementation
    license: MIT
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    bindir: /usr/bin
    contents:
      - src: ./fonts/*.flf
        dst: /usr/share/figlet-go/fonts/
      - src: ./fonts/*.flc
        dst: /usr/share/figlet-go/fonts/
      - src: ./figlet.6
        dst: /usr/share/man/man6/figlet-go.6

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
